### ISSUE TITLE
COIN-1.8 fails to build on Ubuntu 16.10 64-bit 

### ISSUE THREAD

**Issue by ksze** [coin-or/COIN-OR-OptimizationSuite#4]
On Ubuntu 16.10 64-bit, I tried to follow the very simple build instructions here: https://projects.coin-or.org/CoinBinary#BuildingfromSource

However, I got a bunch of errors from g++:
```
In file included from ../include/sym_types.h:31:0,
                 from ../include/sym_master.h:23,
                 from Master/master_func.c:28:
Master/master_func.c: In function 'int set_param(sym_environment*, char*)':
../include/sym_constants.h:334:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedantic]
 }
 ^
Master/master_func.c:1792:42: note: in expansion of macro 'COLGEN_STR_ARRAY'
    str_int colgen_str[COLGEN_STR_SIZE] = COLGEN_STR_ARRAY;
                                          ^~~~~~~~~~~~~~~~
../include/sym_constants.h:334:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedantic]
 }
 ^
Master/master_func.c:1792:42: note: in expansion of macro 'COLGEN_STR_ARRAY'
    str_int colgen_str[COLGEN_STR_SIZE] = COLGEN_STR_ARRAY;
                                          ^~~~~~~~~~~~~~~~
../include/sym_constants.h:334:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedantic]
 }
 ^
Master/master_func.c:1792:42: note: in expansion of macro 'COLGEN_STR_ARRAY'
    str_int colgen_str[COLGEN_STR_SIZE] = COLGEN_STR_ARRAY;
                                          ^~~~~~~~~~~~~~~~
../include/sym_constants.h:334:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedantic]
 }
 ^
Master/master_func.c:1792:42: note: in expansion of macro 'COLGEN_STR_ARRAY'
    str_int colgen_str[COLGEN_STR_SIZE] = COLGEN_STR_ARRAY;
                                          ^~~~~~~~~~~~~~~~
../include/sym_constants.h:334:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedantic]
 }
 ^
Master/master_func.c:1792:42: note: in expansion of macro 'COLGEN_STR_ARRAY'
    str_int colgen_str[COLGEN_STR_SIZE] = COLGEN_STR_ARRAY;
                                          ^~~~~~~~~~~~~~~~
../include/sym_constants.h:358:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedantic]
 }
 ^
Master/master_func.c:1793:52: note: in expansion of macro 'COMPARE_CAN_STR_ARRAY'
    str_int compare_can_str[COMPARE_CAN_STR_SIZE] = COMPARE_CAN_STR_ARRAY;
                                                    ^~~~~~~~~~~~~~~~~~~~~
../include/sym_constants.h:358:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedantic]
 }
 ^
Master/master_func.c:1793:52: note: in expansion of macro 'COMPARE_CAN_STR_ARRAY'
    str_int compare_can_str[COMPARE_CAN_STR_SIZE] = COMPARE_CAN_STR_ARRAY;
                                                    ^~~~~~~~~~~~~~~~~~~~~
../include/sym_constants.h:358:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedantic]
 }
 ^
Master/master_func.c:1793:52: note: in expansion of macro 'COMPARE_CAN_STR_ARRAY'
    str_int compare_can_str[COMPARE_CAN_STR_SIZE] = COMPARE_CAN_STR_ARRAY;
                                                    ^~~~~~~~~~~~~~~~~~~~~
../include/sym_constants.h:358:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedantic]
 }
 ^
Master/master_func.c:1793:52: note: in expansion of macro 'COMPARE_CAN_STR_ARRAY'
    str_int compare_can_str[COMPARE_CAN_STR_SIZE] = COMPARE_CAN_STR_ARRAY;
                                                    ^~~~~~~~~~~~~~~~~~~~~
../include/sym_constants.h:358:1: error: ISO C++ forbids converting a string constant to 'char*' [-Wpedantic]
 }
```

My g++ version is:
```
g++ (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tkralphs** [comment]
Thanks for the report. The same bug was reported [here](https://github.com/coin-or/SYMPHONY/issues/2) and fixed already in SYMPHONY trunk. I just merged it now to stable/5.6 so you should be able to build 1.8 now.
